# Generated by Django 3.2.6 on 2021-08-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notgym', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='classdetails',
            field=models.ManyToManyField(to='notgym.Classdetail'),
        ),
    ]
