# Generated by Django 3.2.6 on 2021-08-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notgym', '0003_category_classdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='classdetails',
        ),
        migrations.AddField(
            model_name='classdetail',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='notgym.Category'),
        ),
    ]
