# Generated by Django 3.2.6 on 2021-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notgym', '0004_auto_20210824_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetail',
            name='blurb',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='type',
            field=models.CharField(default='', max_length=60),
        ),
    ]
