# Generated by Django 3.2.6 on 2021-08-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notgym', '0006_classdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetail',
            name='user',
        ),
    ]
