# Generated by Django 3.2.6 on 2021-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notgym', '0009_classdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetail',
            name='lat',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='classdetail',
            name='lng',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=16),
        ),
    ]
