# Generated by Django 3.2.6 on 2021-08-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notgym', '0011_auto_20210825_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetail',
            name='lat',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='classdetail',
            name='lng',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=15),
        ),
    ]
