# Generated by Django 3.2.6 on 2021-08-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notgym', '0014_auto_20210825_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetail',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='classdetail',
            name='lng',
        ),
    ]
