# Generated by Django 3.2.6 on 2021-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notgym', '0015_auto_20210825_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetail',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9),
        ),
    ]
