# Generated by Django 3.2.6 on 2021-08-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notgym', '0018_auto_20210825_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetail',
            name='categories',
            field=models.ManyToManyField(related_name='classdetails', to='notgym.Category'),
        ),
    ]
